version: '3'
services:
  javademoapp:
    image: javademoapp
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      - CUSTOM_PROPERTY=My custom property
      - SERVER_PORT=8080
      - DATASOURCE_USERNAME=sa
      - DATASOURCE_PASSWORD=difficultpassword